### ISSUE TITLE
Plugin loads but doesn't display anything

### ISSUE THREAD

**Issue by nweddell** [JamFfm/cbpi4-LCDisplay#6]
I've recently installed CBPI4 after using CBPI3 for about a year without any problems.  The LCD worked fine with CBPI3.

The plugin loads fine, no errors and the i2c address is recognised but nothing appears on the display.  When the CBPI server is stopped I get the following error:

2022-06-14:13:22:00,928 ERROR    [base_events.py:1738] Task exception was never retrieved
future: <Task finished name='Task-5' coro=<LCDisplay.run() done, defined at /usr/local/lib/python3.9/dist-packages/cbpi4-LCDisplay/__init__.py:127> exception=TypeError("'NoneType' object is not subscriptable")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/cbpi4-LCDisplay/__init__.py", line 167, in run
    sensor_for_sensor_mode = await self.set_lcd_sensortype_for_sensor_mode()
  File "/usr/local/lib/python3.9/dist-packages/cbpi4-LCDisplay/__init__.py", line 588, in set_lcd_sensortype_for_sensor_mode
    sensor_type = (sensor_values["sensor_type"])
TypeError: 'NoneType' object is not subscriptable

I've done a number of clean installs of CBPI4 and re-installs of the plugin but the error persists.  Any ideas?

Many thanks in advance.

Nick

**Comment by avollkopf** [comment]
@nweddell Did you also try my fork of the plugin? I have it running on my system, and it is working fine for brewing and fermentation.

**Comment by JamFfm** [comment]
Hi I do recommend Alexander’s fork as he is more active and if you use fermentation this is the way to go.  For me it takes some time to check an I am a bit out of practice as I had a lot private problems lately. 


Von meinem iPhone gesendet

Grüße Jan Battermann
